### ISSUE TITLE
SageEmbed: Cannot change search query

### ISSUE THREAD

**Issue by ZZNK** [thoughtspot/visual-embed-sdk#1046]
Using SageEmbed react component: when I first type out a query it works fine but after the execution I cannot edit it or type in anything else. I can clear the search bar but when trying to type in any character the entire previous query shows up. 

The same thing seems to be a problem in thoughtspot playground.

The issue persists with or without params in the SageEmbed component and also with different worksheets.

**Comment by mouryab** [comment]
@ZZNK Can you let us know the Thoughtspot cluster version

**Comment by ZZNK** [comment]
I was unable to find anything about clusters in the admin tab but does this answer your questions? 
![image](https://github.com/thoughtspot/visual-embed-sdk/assets/114572120/b2cc7e1d-2234-4c84-a06c-20cf268a1124)

**Comment by mouryab** [comment]
I fixed this in the recent patch and I am unable to replicate it anymore on my end but I would like to make sure if this is a new issue.

Can you provide the cluster details. I will work with our SRE to setup a zoom call to debug this issue if needed.

**Comment by ZZNK** [comment]
I can see that in the playground link provided in the docs, the problem has been fixed. However I am still experiencing the issue in our TS environment playground and in the embedded component.

Can you provide the version where this seems to be working? With v1.26.6 being the latest, none of them (including 1.27.0-alpha.x versions) show any change.

In the thought spot docs I found multiple mentions of clusters in TS software section but no mention of it in TS cloud which is what i am using. The provided screenshot is the only mention in the environment of a version as far as I know. Can you point me to where I can find the cluster details? I do have admin access to the environment.

**Comment by mouryab** [comment]
@ZZNK thanks for the detail. Appreciate it. The https://github.com/thoughtspot/visual-embed-sdk is currently up to date. The patch seems to be missing on the TS cluster itself. Can you provide the company name. I will work with our SRE team to get the patch merged in the cluster.

**Comment by mouryab** [comment]
@ZZNK Can you let us know when we can apply the patch? We can have our SRE trigger it or COA team can do it at a specific time. Since this upgrade window will impact userability and accessibilty,  we recommend updating after business hours.

**Comment by ZZNK** [comment]
@mouryab if the update is going to take just a few minutes please do it asap, if not then anything outside of 9am to 6pm CST is okay
thank you

**Comment by ZZNK** [comment]
@mouryab hello, any updates on this?

**Comment by mouryab** [comment]
Confirmed with customer that patch was applied on March 4 and working as expected.
